backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Matches Jekyll's strict naming rule
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}